## General pipeline parameters:
## For optional parameters either leave empty string ("") or comment out ("#") the parameter

# working directory (required):
workdir: ""

# prefix of all output files (optional; default = "sample")
sample_name: ""

# reference genome (required)
genome: "/references/GRCh38.primary_assembly.genome.fa"

# input subreads BAM
input_bam: ""

# primers in fasta format
primers: "/primers.fa"

# threads (default = 30)
threads: 30

# complete path to sqanti tool (required)
sqanti_dir: "/Tools/SQANTI3-4.2"

# input annotation data required for sqanti (required)
# make sure the contig names in the annotation matches the input genome file
gtf: "/gencode.v38.annotation.gtf"
cage: "/refTSS_v3.3_human_coordinate.hg38.bed"
intropolis: "/intropolis.v1.hg19_with_liftover_to_hg38.min_count_10.tsv"
polya_atlas: "/atlas.clusters.2.0.GRCh38.96.mod.bed"

# Genes of interest (optional; default = ""): Only the reads overlapping the gene locus will be selected from the SAM file.
# format: gene_id of genes from the GTF file provided
# multiple genes can be provided seperated by a ";". For e.g., "ENSG00000145335.17;ENSG00000247775.2"
genes: "ENSG00000145335.17"


